# Generated by Django 5.1.3 on 2024-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
